---
- name: Remove java 11
  yum:
    name: "{{ packages }}"
    state: removed
  vars:
    packages:
    - java-11-amazon-corretto-headless

- name: Install minecraft and service dependencies
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - java-17-amazon-corretto-headless
    - git
    - python3

- name: add minecraft service to systemd
  copy:
    remote_src: yes
    src: /mnt/efs/minecraft/minecraft@.service
    dest: /etc/systemd/system/minecraft@.service
    force: yes


- name: reload the daemon and enable/start the minecraft service
  systemd:
    daemon_reload: yes
    name: minecraft@0
    enabled: yes
    state: started
